Skip existing repos in clone-salt-org

diff --git a/clone-salt-org b/clone-salt-org
--- a/clone-salt-org
+++ b/clone-salt-org
@@ -1,20 +1,32 @@
 #!/bin/bash
+# -*- sh-shell: bash; sh-indentation: 8; tab-width: 8; indent-tabs-mode: t; -*-
 # needs curl and jq
 
 if (( $# < 1)); then
-    echo "usage: clone-salt-org <dir>"
-    echo "  <dir>: directory where repos are cloned into"
-    exit 1
+	echo "usage: clone-salt-org <dir>"
+	echo "  <dir>: directory where repos are cloned into"
+	exit 1
 fi
 
+for cmd in curl jq git; do
+	if ! command -v $cmd &> /dev/null; then
+		echo "$cmd could not be found"
+		exit 1
+	fi
+done
+
 workdir=${1}
-repos=($(curl --silent https://src.opensuse.org/api/v1/orgs/salt/repos | jq -r '.[].name'))
+readarray -t repos < <(curl --silent --fail "https://src.opensuse.org/api/v1/orgs/salt/repos?limit=1000" | jq -r '.[].name')
 
 if [[ ! -d "$workdir" ]]; then
-    mkdir -p "$workdir" || exit 1
+	mkdir -p "$workdir" || exit 1
 fi
 
 cd "$workdir" || exit 1
 for repo in "${repos[@]}"; do
-    git clone gitea@src.opensuse.org:salt/"$repo"
+	if [[ -d "$repo" ]]; then
+		echo "Skipping $repo: already exists"
+	else
+		git clone gitea@src.opensuse.org:salt/"$repo"
+	fi
 done
